branch-defaults:
  PSU-4-add-create-post-functionality:
    environment: psu-healthy-wealthy-prod-backend
    group_suffix: null
  main:
    environment: psu-healthy-wealthy-prod-backend
global:
  application_name: psu-healthy-wealthy
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
