name: Node.js CI/CD

on:
  push:
    branches: 
    - PSU-20-add-backend-code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "us-west-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://healthy-wealthy-backend-deploy-2024/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name HealthyWealthyBackend \
          --source-bundle S3Bucket="healthy-wealthy-backend-deploy-2024",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name healthy-wealthy-prod-env --version-label "ver-${{ github.sha }}"